
# 站点主结构树
site_tree:
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: recent # for categories/tags/archives
    rightbar: ghrepo
    nav_tabs: # 近期发布 分类 标签 专栏 归档 and ...
      "新闻": /news/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: ghissues, related, recent # for wiki
    rightbar: ghrepo
    nav_tabs:
  # 博客文章内页配置
  home:
    leftbar: welcome, announcement
    rightbar: comment, tagcloud
  post:
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: related, recent # for pages using 'layout:post'
    rightbar: ghrepo, toc
  # 博客专栏文章内页配置
  topic:
    menu_id: post
  # 文档内页配置
  wiki:
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: tree
    rightbar: ghrepo, toc
  # 错误页配置
  error_page:
    menu_id: post
    "404": "/404.html"
    leftbar: recent
    rightbar: tagcloud
  # 其它自定义页面配置 layout: page
  page:
    leftbar: recent
    rightbar: timeline

open_graph:
  enable: false
  twitter_id: # for open_graph meta

article:
  type: tech # tech/story: story类文字和段落间增距大。
  auto_cover: false # 根据tags在线搜索封面
  auto_description: 20 # 生成摘要的字
  related_posts:
    enable: true
    title: 您可能感兴趣的文章
    max_count: 2
  license: false
  share: [wechat, weibo, email, link]
# 全局样式
style:
  prefers_theme: light
  color:
    # 动态颜色（会根据明暗主题重设明度值，只用关心色相和饱和度即可）
    background: "hsl(212 16% 98%)" # 浅色背景颜色
    block: "hsl(212 8% 95%)" # 块背景颜色
    code: "hsl(14 100% 48%)" # 行内代码颜色
    text: "hsl(0 0% 20%)" # 文本颜色
    # 主题色配置（不会根据明暗动态调整，请设置为通用的颜色）
    theme: "hsl(192 98% 55%)" # 主题色
    accent: "hsl(14 100% 57%)" # 强调色
    link: "hsl(207 90% 54%)" # 超链接颜色
    button: "hsl(192 98% 55%)" # 按钮颜色
    hover: "hsl(14 100% 57%)" # 按钮高亮颜色
  leftbar:
    blur-px: 0px
    blur-bg: var(--alpha60)
    background-image: url(https://mobile-img-baofun.zhhainiao.com/pcwallpaper_ugc_mobile/live/6f13fea4efc75aee7d80db85bd796d96_preview_mid.jpg)
  text-align: left # justify/left/center/right
  prefix:
    h2: https://api.iconify.design/ci:heading-h2.svg
  darkmode: auto # auto true false
  font-size:
    root: 17.5px # 改这个会影响全局所有文字的字号
    body: 18px # 影响正文区域的字号，如果改成 px 则不受 root 影响
    code: 70% # 相较于其所在行的文本大小，建议用百分比
    codeblock: 0.7rem # 13px
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
  border-radius:
    card-l: 16px # 侧边栏、文章横幅位置的圆角
    card: 12px # 文章内大部分卡片的圆角
    bar: 8px # 横条类元素的圆角
    image: 12px # 图片圆角
  codeblock:
    scrollbar: 4px
    highlightjs_theme: /vendor/css/atom-one-dark.min.css


comments:
  service: giscus
  # giscus
  # https://giscus.app/zh-CN
  giscus:
    src: https://giscus.app/client.js
    data-repo: ayellowdogsays/giscus
    data-repo-id: R_kgDONudV-A
    data-category: Announcements
    data-category-id: DIC_kwDONudV-M4CmRWu
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous


